/** Human label e.g. "May 2026" from `YYYY-MM`. */
export function monthKeyToLongLabel(monthKey: string): string {
  const [y, m] = monthKey.split("-").map((v) => Number(v));
  if (!Number.isFinite(y) || !Number.isFinite(m)) return monthKey;
  return new Date(y, m - 1, 1).toLocaleString("en-US", { month: "long", year: "numeric" });
}

export type RoommateShareSettlementLine = { from: string; to: string; amountNpr: number };

export function buildRoommateExpenseSummaryText(input: {
  monthKey: string;
  members: string[];
  memberExpectedShare: Record<string, number>;
  totalExpenseNpr: number;
  equalSplitNpr: number;
  transfers: RoommateShareSettlementLine[];
  formatAmount: (amountNpr: number) => string;
}): string {
  const month = monthKeyToLongLabel(input.monthKey);
  const memberLines = input.members
    .map((name) => `- ${name}: ${input.formatAmount(input.memberExpectedShare[name] ?? 0)}`)
    .join("\n");

  const settlementBlock =
    input.transfers.length > 0
      ? `\nSettlement:\n${input.transfers
          .map((t) => `- ${t.from} → ${t.to}: ${input.formatAmount(t.amountNpr)}`)
          .join("\n")}`
      : "";

  return [
    "Roommate Expense Summary",
    `Month: ${month}`,
    "",
    `Total Expense: ${input.formatAmount(input.totalExpenseNpr)}`,
    `Per Person: ${input.formatAmount(input.equalSplitNpr)}`,
    "",
    "Members:",
    memberLines,
    settlementBlock,
    "",
    "Generated by FIRE Nepal",
  ].join("\n");
}

export function isDesktopShareUi(): boolean {
  if (typeof window === "undefined") return true;
  const fine = window.matchMedia("(pointer: fine)").matches;
  const wide = window.matchMedia("(min-width: 1024px)").matches;
  return fine && wide;
}

export function whatsappShareUrl(text: string): string {
  return `https://api.whatsapp.com/send?text=${encodeURIComponent(text)}`;
}

export function telegramShareUrl(text: string, pageUrl: string): string {
  const u = encodeURIComponent(pageUrl);
  const t = encodeURIComponent(text);
  return `https://t.me/share/url?url=${u}&text=${t}`;
}

/** Facebook web share with quote (works without Messenger app id). */
export function facebookMessengerFriendlyShareUrl(text: string, pageUrl: string): string {
  const u = encodeURIComponent(pageUrl);
  const max = 600;
  const quote = text.length > max ? `${text.slice(0, max - 1)}…` : text;
  return `https://www.facebook.com/sharer/sharer.php?u=${u}&quote=${encodeURIComponent(quote)}`;
}

/**
 * Opens KakaoTalk compose when the app is installed (Korean users abroad).
 * Android uses explicit intent; iOS / others use kakaotalk:// scheme.
 */
export function kakaoTalkShareHref(text: string): string {
  const enc = encodeURIComponent(text);
  if (typeof navigator !== "undefined" && /Android/i.test(navigator.userAgent)) {
    return `intent://send?text=${enc}#Intent;scheme=kakaotalk;package=com.kakao.talk;end`;
  }
  return `kakaotalk://send?text=${enc}`;
}

function wrapLine(ctx: CanvasRenderingContext2D, line: string, maxWidth: number): string[] {
  if (!line.trim()) return [""];
  const words = line.split(/\s+/);
  const lines: string[] = [];
  let current = words[0] ?? "";

  function pushChunk(chunk: string) {
    let s = chunk;
    while (s.length > 0 && ctx.measureText(s).width > maxWidth) {
      let lo = 1;
      let hi = s.length;
      while (lo < hi) {
        const mid = Math.ceil((lo + hi) / 2);
        if (ctx.measureText(s.slice(0, mid)).width <= maxWidth) lo = mid;
        else hi = mid - 1;
      }
      const take = Math.max(1, lo);
      lines.push(s.slice(0, take));
      s = s.slice(take);
    }
    return s;
  }

  current = pushChunk(current);

  for (let i = 1; i < words.length; i++) {
    const w = words[i];
    const test = current.length ? `${current} ${w}` : w;
    if (ctx.measureText(test).width <= maxWidth) {
      current = test;
    } else {
      if (current.length) lines.push(current);
      current = pushChunk(w);
    }
  }
  if (current.length) lines.push(current);
  return lines;
}

function flattenSummaryToCanvasLines(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string[] {
  const out: string[] = [];
  for (const raw of text.split("\n")) {
    const wrapped = wrapLine(ctx, raw, maxWidth);
    out.push(...wrapped);
  }
  return out;
}

export async function downloadSummaryPngImage(text: string, filename: string): Promise<void> {
  const dpr = typeof window !== "undefined" ? Math.min(window.devicePixelRatio || 1, 2) : 1;
  const pad = 48;
  const width = 720;
  const fontSize = 15;
  const lineHeight = Math.round(fontSize * 1.45);

  const canvas = document.createElement("canvas");
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas unsupported");

  ctx.font = `600 ${fontSize}px ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif`;
  const innerW = width - pad * 2;
  const lines = flattenSummaryToCanvasLines(ctx, text, innerW);
  const height = Math.min(2400, pad * 2 + lines.length * lineHeight + 32);

  canvas.width = Math.round(width * dpr);
  canvas.height = Math.round(height * dpr);
  canvas.style.width = `${width}px`;
  canvas.style.height = `${height}px`;

  const c = canvas.getContext("2d");
  if (!c) throw new Error("Canvas unsupported");
  c.scale(dpr, dpr);
  c.fillStyle = "#ecfdf5";
  c.fillRect(0, 0, width, height);

  const cardX = 28;
  const cardY = 28;
  const cardW = width - 56;
  const cardH = height - 56;
  c.fillStyle = "#ffffff";
  c.shadowColor = "rgba(0, 80, 40, 0.12)";
  c.shadowBlur = 28;
  c.shadowOffsetY = 10;
  const r = 20;
  c.beginPath();
  c.moveTo(cardX + r, cardY);
  c.lineTo(cardX + cardW - r, cardY);
  c.quadraticCurveTo(cardX + cardW, cardY, cardX + cardW, cardY + r);
  c.lineTo(cardX + cardW, cardY + cardH - r);
  c.quadraticCurveTo(cardX + cardW, cardY + cardH, cardX + cardW - r, cardY + cardH);
  c.lineTo(cardX + r, cardY + cardH);
  c.quadraticCurveTo(cardX, cardY + cardH, cardX, cardY + cardH - r);
  c.lineTo(cardX, cardY + r);
  c.quadraticCurveTo(cardX, cardY, cardX + r, cardY);
  c.closePath();
  c.fill();
  c.shadowColor = "transparent";

  c.fillStyle = "#064e3b";
  c.font = `600 ${fontSize}px ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif`;
  let y = cardY + pad;
  for (const line of lines) {
    c.fillText(line, cardX + pad, y);
    y += lineHeight;
  }

  await new Promise<void>((resolve, reject) => {
    canvas.toBlob(
      (blob) => {
        if (!blob) {
          reject(new Error("PNG export failed"));
          return;
        }
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = filename.endsWith(".png") ? filename : `${filename}.png`;
        a.click();
        URL.revokeObjectURL(url);
        resolve();
      },
      "image/png",
      0.92,
    );
  });
}

export async function downloadSummaryPdf(text: string, filename: string): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 18;
  const pageW = doc.internal.pageSize.getWidth();
  const maxW = pageW - margin * 2;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(6, 78, 59);

  const lines = doc.splitTextToSize(text, maxW);
  let y = margin;
  const lineH = 6;
  const pageH = doc.internal.pageSize.getHeight();

  for (const line of lines) {
    if (y > pageH - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += lineH;
  }

  doc.save(filename.endsWith(".pdf") ? filename : `${filename}.pdf`);
}
