import type { Currency } from "@/lib/expense-utils";
import { FALLBACK_KRW_PER_NPR } from "@/lib/exchange-rate";
import { downloadSummaryPdf, monthKeyToLongLabel } from "@/lib/roommate-expense-share";

export type SettlementShareMemberLine = {
  memberId: string;
  name: string;
  balanceNpr: number;
  signedLabel: string;
  role: "receives" | "pays" | "settled";
};

export type SettlementShareTransferLine = {
  fromName: string;
  toName: string;
  amountLabel: string;
};

export type SettlementShareData = {
  monthKey: string;
  monthLabel: string;
  currency: Currency;
  members: SettlementShareMemberLine[];
  transfers: SettlementShareTransferLine[];
  siteUrl: string;
};

const FIRE_NEPAL_SITE = "https://firenepal.com";

export function defaultSettlementSiteUrl(): string {
  if (typeof window !== "undefined" && window.location.origin) {
    return window.location.origin;
  }
  return FIRE_NEPAL_SITE;
}

function currencyMetaLive(krwPerNpr: number) {
  return {
    NPR: { symbol: "रु", rate: 1 },
    KRW: { symbol: "₩", rate: krwPerNpr },
    USD: { symbol: "$", rate: 0.0075 },
  };
}

function fmtAmount(npr: number, currency: Currency, krwPerNpr: number) {
  const meta = currencyMetaLive(krwPerNpr)[currency];
  const converted = npr * meta.rate;
  const maximumFractionDigits = currency === "USD" ? 2 : 0;
  return `${meta.symbol} ${converted.toLocaleString("en-US", { maximumFractionDigits })}`;
}

function fmtSignedAmount(npr: number, currency: Currency, krwPerNpr: number) {
  const meta = currencyMetaLive(krwPerNpr)[currency];
  const converted = Math.abs(npr) * meta.rate;
  const maximumFractionDigits = currency === "USD" ? 2 : 0;
  const value = converted.toLocaleString("en-US", { maximumFractionDigits });
  if (npr > 1) return `+${meta.symbol}${value}`;
  if (npr < -1) return `-${meta.symbol}${value}`;
  return `${meta.symbol}${value}`;
}

function fmtAbsAmount(npr: number, currency: Currency, krwPerNpr: number) {
  return fmtSignedAmount(npr, currency, krwPerNpr).replace(/^[+-]/, "");
}

export function buildSettlementShareData(input: {
  monthKey: string;
  members: string[];
  memberLabels: Record<string, string>;
  balances: Record<string, number>;
  transfers: Array<{ from: string; to: string; amount: number }>;
  transferLabels: Array<{ fromName: string; toName: string }>;
  currency: Currency;
  krwPerNpr?: number;
  siteUrl?: string;
}): SettlementShareData {
  const krwPerNpr = input.krwPerNpr ?? FALLBACK_KRW_PER_NPR;

  const memberLines: SettlementShareMemberLine[] = input.members.map((memberId) => {
    const balanceNpr = input.balances[memberId] ?? 0;
    const name = input.memberLabels[memberId] ?? memberId;
    if (Math.abs(balanceNpr) < 1) {
      return {
        memberId,
        name,
        balanceNpr,
        signedLabel: fmtAmount(0, input.currency, krwPerNpr),
        role: "settled",
      };
    }
    if (balanceNpr > 0) {
      return {
        memberId,
        name,
        balanceNpr,
        signedLabel: fmtSignedAmount(balanceNpr, input.currency, krwPerNpr),
        role: "receives",
      };
    }
    return {
      memberId,
      name,
      balanceNpr,
      signedLabel: fmtSignedAmount(balanceNpr, input.currency, krwPerNpr),
      role: "pays",
    };
  });

  const transfers: SettlementShareTransferLine[] = input.transfers.map((t, i) => ({
    fromName: input.transferLabels[i]?.fromName ?? t.from,
    toName: input.transferLabels[i]?.toName ?? t.to,
    amountLabel: fmtAmount(t.amount, input.currency, krwPerNpr),
  }));

  return {
    monthKey: input.monthKey,
    monthLabel: monthKeyToLongLabel(input.monthKey),
    currency: input.currency,
    members: memberLines,
    transfers,
    siteUrl: input.siteUrl ?? defaultSettlementSiteUrl(),
  };
}

export function buildSettlementShareCardText(data: SettlementShareData): string {
  const memberBlock = data.members.map((m) => `- ${m.name} ${m.signedLabel}`).join("\n");
  const transferBlock =
    data.transfers.length > 0
      ? data.transfers.map((t) => `${t.fromName} → ${t.toName} ${t.amountLabel}`).join("\n")
      : "All settled — no transfers needed";

  return [
    "🏠 Roommate Settlement Summary",
    "",
    "Month:",
    data.monthLabel,
    "",
    "Members:",
    memberBlock,
    "",
    "Transfers:",
    transferBlock,
    "",
    "Generated by FIRE Nepal",
  ].join("\n");
}

export function buildSettlementShareSocialMessage(
  data: SettlementShareData,
  krwPerNpr = FALLBACK_KRW_PER_NPR,
): string {
  const receivers = data.members.filter((m) => m.role === "receives");
  const payers = data.members.filter((m) => m.role === "pays");

  const parts = ["🏠 Roommate Settlement Summary", ""];

  if (receivers.length) {
    parts.push(
      receivers
        .map((m) => `${m.name} receives ${fmtAbsAmount(m.balanceNpr, data.currency, krwPerNpr)}`)
        .join("\n\n"),
      "",
    );
  }

  if (payers.length) {
    parts.push(
      payers.map((m) => `${m.name} pays ${fmtAbsAmount(m.balanceNpr, data.currency, krwPerNpr)}`).join("\n"),
      "",
    );
  }

  if (!receivers.length && !payers.length) {
    parts.push("Everyone is settled for this month.", "");
  }

  parts.push("Generated with FIRE Nepal", data.siteUrl || FIRE_NEPAL_SITE);
  return parts.join("\n");
}

export function lineShareUrl(text: string): string {
  return `https://line.me/R/share?text=${encodeURIComponent(text)}`;
}

function drawSettlementCard(
  ctx: CanvasRenderingContext2D,
  data: SettlementShareData,
  width: number,
  height: number,
) {
  const pad = 40;
  const lineH = 26;
  const sectionGap = 18;

  const bg = ctx.createLinearGradient(0, 0, width, height);
  bg.addColorStop(0, "#064e3b");
  bg.addColorStop(1, "#047857");
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, width, height);

  const cardX = 24;
  const cardY = 24;
  const cardW = width - 48;
  const cardH = height - 48;
  const r = 24;
  ctx.fillStyle = "#ffffff";
  ctx.shadowColor = "rgba(0, 50, 30, 0.25)";
  ctx.shadowBlur = 32;
  ctx.shadowOffsetY = 12;
  ctx.beginPath();
  ctx.moveTo(cardX + r, cardY);
  ctx.lineTo(cardX + cardW - r, cardY);
  ctx.quadraticCurveTo(cardX + cardW, cardY, cardX + cardW, cardY + r);
  ctx.lineTo(cardX + cardW, cardY + cardH - r);
  ctx.quadraticCurveTo(cardX + cardW, cardY + cardH, cardX + cardW - r, cardY + cardH);
  ctx.lineTo(cardX + r, cardY + cardH);
  ctx.quadraticCurveTo(cardX, cardY + cardH, cardX, cardY + cardH - r);
  ctx.lineTo(cardX, cardY + r);
  ctx.quadraticCurveTo(cardX, cardY, cardX + r, cardY);
  ctx.closePath();
  ctx.fill();
  ctx.shadowColor = "transparent";

  const innerX = cardX + pad;
  let y = cardY + pad + 8;
  const innerW = cardW - pad * 2;

  ctx.textAlign = "left";
  ctx.fillStyle = "#065f46";
  ctx.font = "800 22px ui-sans-serif, system-ui, -apple-system, sans-serif";
  ctx.fillText("🏠 Roommate Settlement Summary", innerX, y);
  y += 36;

  ctx.font = "600 12px ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = "#64748b";
  ctx.fillText("MONTH", innerX, y);
  y += 18;
  ctx.font = "700 18px ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = "#064e3b";
  ctx.fillText(data.monthLabel, innerX, y);
  y += sectionGap + 8;

  ctx.font = "700 11px ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = "#64748b";
  ctx.fillText("MEMBERS", innerX, y);
  y += 22;

  for (const member of data.members) {
    ctx.font = "600 15px ui-sans-serif, system-ui, sans-serif";
    ctx.fillStyle = "#0f172a";
    ctx.fillText(member.name, innerX, y);
    ctx.textAlign = "right";
    ctx.font = "700 15px ui-sans-serif, system-ui, sans-serif";
    if (member.role === "receives") ctx.fillStyle = "#047857";
    else if (member.role === "pays") ctx.fillStyle = "#dc2626";
    else ctx.fillStyle = "#64748b";
    ctx.fillText(member.signedLabel, innerX + innerW, y);
    ctx.textAlign = "left";
    y += lineH;
  }

  y += 8;
  ctx.font = "700 11px ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = "#64748b";
  ctx.fillText("TRANSFERS", innerX, y);
  y += 22;

  if (data.transfers.length === 0) {
    ctx.font = "600 14px ui-sans-serif, system-ui, sans-serif";
    ctx.fillStyle = "#047857";
    ctx.fillText("All settled — no transfers needed", innerX, y);
  } else {
    for (const transfer of data.transfers) {
      ctx.font = "600 14px ui-sans-serif, system-ui, sans-serif";
      ctx.fillStyle = "#334155";
      ctx.fillText(`${transfer.fromName} → ${transfer.toName}`, innerX, y);
      ctx.textAlign = "right";
      ctx.font = "700 14px ui-sans-serif, system-ui, sans-serif";
      ctx.fillStyle = "#065f46";
      ctx.fillText(transfer.amountLabel, innerX + innerW, y);
      ctx.textAlign = "left";
      y += lineH;
    }
  }

  ctx.textAlign = "center";
  ctx.font = "600 11px ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = "#94a3b8";
  ctx.fillText("Generated by FIRE Nepal", cardX + cardW / 2, cardY + cardH - pad);
}

function settlementCardHeight(data: SettlementShareData): number {
  const pad = 40;
  const lineH = 26;
  const sectionGap = 18;
  const memberRows = data.members.length;
  const transferRows = Math.max(data.transfers.length, 1);
  return Math.min(2000, pad * 2 + 120 + memberRows * lineH + sectionGap + 28 + transferRows * lineH + 56);
}

function createSettlementCardCanvas(data: SettlementShareData) {
  const dpr = typeof window !== "undefined" ? Math.min(window.devicePixelRatio || 1, 2) : 1;
  const width = 720;
  const height = settlementCardHeight(data);
  const canvas = document.createElement("canvas");
  canvas.width = Math.round(width * dpr);
  canvas.height = Math.round(height * dpr);
  canvas.style.width = `${width}px`;
  canvas.style.height = `${height}px`;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas unsupported");
  ctx.scale(dpr, dpr);
  drawSettlementCard(ctx, data, width, height);
  return canvas;
}

export async function settlementSharePngBlob(data: SettlementShareData): Promise<Blob> {
  const canvas = createSettlementCardCanvas(data);
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => (blob ? resolve(blob) : reject(new Error("PNG export failed"))),
      "image/png",
      0.94,
    );
  });
}

export async function downloadSettlementSharePng(data: SettlementShareData, filename: string): Promise<void> {
  const blob = await settlementSharePngBlob(data);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".png") ? filename : `${filename}.png`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function downloadSettlementSharePdf(data: SettlementShareData, filename: string): Promise<void> {
  await downloadSummaryPdf(buildSettlementShareCardText(data), filename);
}
