import type { PensionPolicyRule } from "@/lib/pension-policy/types";

/** SSF (Social Security Fund) — qualitative scheme structure + portals. Numeric rates pending official rate-page verification. */
export const SSF_POLICY_RULES: PensionPolicyRule[] = [
  {
    id: "ssf-scheme-medical-maternity-v1",
    institution: "ssf",
    policyServiceName: "Medical Treatment, Health and Maternity Protection Scheme",
    officialSourceUrl: "https://ssf.gov.np/",
    ruleCategory: "medical",
    effectiveDate: "2017-11-12",
    version: "ssf-scheme-v1",
    lastVerifiedDate: "2026-08-15",
    status: "active",
    title: "Medical & maternity protection scheme",
    summary:
      "SSF operates a medical treatment, health and maternity protection scheme for enrolled contributors under the contribution-based social security framework.",
    notes: "Claim procedures and coverage limits must be confirmed on the official SSF portal before planning cash amounts.",
  },
  {
    id: "ssf-scheme-accident-disability-v1",
    institution: "ssf",
    policyServiceName: "Accident and Disability Protection Scheme",
    officialSourceUrl: "https://ssf.gov.np/",
    ruleCategory: "accident_disability",
    effectiveDate: "2017-11-12",
    version: "ssf-scheme-v1",
    lastVerifiedDate: "2026-08-15",
    status: "active",
    title: "Accident & disability protection scheme",
    summary:
      "SSF provides accident and disability-related social security protection for eligible enrolled contributors.",
  },
  {
    id: "ssf-scheme-dependent-family-v1",
    institution: "ssf",
    policyServiceName: "Dependent Family Protection Scheme",
    officialSourceUrl: "https://ssf.gov.np/",
    ruleCategory: "family_protection",
    effectiveDate: "2017-11-12",
    version: "ssf-scheme-v1",
    lastVerifiedDate: "2026-08-15",
    status: "active",
    title: "Dependent / family protection scheme",
    summary:
      "SSF includes dependent family protection benefits for eligible survivors/dependents of enrolled contributors.",
  },
  {
    id: "ssf-scheme-old-age-v1",
    institution: "ssf",
    policyServiceName: "Old Age Protection Scheme",
    officialSourceUrl: "https://ssf.gov.np/",
    ruleCategory: "retirement_benefit",
    effectiveDate: "2017-11-12",
    version: "ssf-scheme-v1",
    lastVerifiedDate: "2026-08-15",
    status: "active",
    title: "Old-age / retirement protection scheme",
    summary:
      "SSF old-age protection covers retirement-oriented benefits for eligible long-term contributors. Exact pension formulas are published by SSF and must be read from official materials.",
  },
  {
    id: "ssf-eligibility-enrollment-v1",
    institution: "ssf",
    policyServiceName: "Contributor & employer enrollment",
    officialSourceUrl: "https://ssf.gov.np/",
    ruleCategory: "eligibility",
    effectiveDate: "2017-11-12",
    version: "ssf-eligibility-v1",
    lastVerifiedDate: "2026-08-15",
    status: "active",
    title: "Enrollment via official SSF / SOSYS portals",
    summary:
      "Employers and contributors register and manage membership through official SSF systems (ssf.gov.np / sosys.ssf.gov.np). Each contributor receives an official SSF identity after verification.",
  },
  {
    id: "ssf-contribution-rates-pending",
    institution: "ssf",
    policyServiceName: "Contribution rates",
    officialSourceUrl: "https://ssf.gov.np/",
    ruleCategory: "contribution",
    effectiveDate: "2017-11-12",
    version: "ssf-contribution-pending",
    lastVerifiedDate: "2026-08-15",
    status: "pending_verification",
    title: "Contribution rate schedule",
    summary:
      "Employee and employer contribution percentages for SSF schemes must be confirmed from the current official SSF notification / Act schedule before use in calculators.",
    notes: "Do not apply a numeric rate in FireNepal until a verified official rate table version is activated.",
  },
  {
    id: "ssf-withdrawal-claims-pending",
    institution: "ssf",
    policyServiceName: "Withdrawal and claim procedures",
    officialSourceUrl: "https://sosys.ssf.gov.np/",
    ruleCategory: "withdrawal",
    effectiveDate: "2017-11-12",
    version: "ssf-withdrawal-pending",
    lastVerifiedDate: "2026-08-15",
    status: "pending_verification",
    title: "Withdrawal / claim rules",
    summary:
      "Benefit claims and any withdrawal-like actions are processed through official SSF portals and rules. Numeric limits are not embedded here until verified.",
  },
];
