import { formatBizNpr } from "@/lib/fire-biz/i18n";
import { parseLineItems } from "@/lib/fire-biz/line-items";
import { computeVatFromSale } from "@/lib/fire-biz/vat";
import type { BusinessProfileRow, CustomerRow, SaleRow } from "@/lib/fire-biz/types";

export type InvoicePdfInput = {
  sale: SaleRow;
  profile: BusinessProfileRow | null;
  customer: CustomerRow | null;
};

export async function downloadInvoicePdf({ sale, profile, customer }: InvoicePdfInput): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 14;
  let y = margin;
  const pageW = doc.internal.pageSize.getWidth();
  const maxW = pageW - margin * 2;

  const line = (text: string, gap = 5, fontSize = 10) => {
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, maxW);
    for (const ln of lines) {
      if (y > 285) {
        doc.addPage();
        y = margin;
      }
      doc.text(ln, margin, y);
      y += gap;
    }
  };

  // Header band
  doc.setFillColor(16, 185, 129);
  doc.rect(0, 0, pageW, 28, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text("FIRE Nepal — Tax Invoice", margin, 14);
  doc.setFontSize(10);
  doc.text(profile?.business_name ?? "Business", margin, 22);
  doc.setTextColor(30, 30, 30);
  y = 36;

  line(`Invoice: ${sale.invoice_number ?? sale.id.slice(0, 8)}`, 5, 12);
  line(`Date: ${sale.sale_date}`, 5);
  line(`Payment: ${sale.payment_status} · ${sale.payment_method ?? "cash"}`, 5);

  if (profile?.pan_vat) line(`VAT/PAN: ${profile.pan_vat}`, 5);
  if (profile?.address) line(`Address: ${profile.address}`, 5);
  if (profile?.phone) line(`Phone: ${profile.phone}`, 5);

  y += 4;
  line("Bill To:", 5, 11);
  line(customer?.name ?? "Walk-in Customer", 5);
  if (customer?.phone) line(`Phone: ${customer.phone}`, 5);
  if (customer?.address) line(`Address: ${customer.address}`, 5);

  y += 6;
  doc.setDrawColor(16, 185, 129);
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  const items = parseLineItems(sale.line_items);
  line("Item                          Qty    Rate         Amount", 5, 9);
  y += 2;
  for (const item of items) {
    const amt = item.quantity * item.unitPrice - (item.discount ?? 0);
    line(
      `${item.name.slice(0, 28).padEnd(28)} ${String(item.quantity).padStart(3)}  ${formatBizNpr(item.unitPrice).padStart(10)}  ${formatBizNpr(amt).padStart(12)}`,
      5,
      9,
    );
  }

  y += 4;
  const vat = computeVatFromSale(sale);
  line(`Subtotal: ${formatBizNpr(Number(sale.subtotal) || vat.subtotal)}`, 5);
  if (Number(sale.discount_amount) > 0) line(`Discount: ${formatBizNpr(Number(sale.discount_amount))}`, 5);
  if (sale.is_tax_invoice) {
    line(`Taxable: ${formatBizNpr(vat.taxableAmount)}`, 5);
    line(`VAT (${vat.vatRate}%): ${formatBizNpr(Number(sale.tax_amount) || vat.vatAmount)}`, 5);
  }
  line(`Total: ${formatBizNpr(Number(sale.total_amount))}`, 6, 12);
  line(`Paid: ${formatBizNpr(Number(sale.amount_paid))}`, 5);
  line(`Due: ${formatBizNpr(Number(sale.total_amount) - Number(sale.amount_paid))}`, 5);

  y += 8;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  line("Generated by FIRE Biz · firenepal.com", 4);
  line("This is a computer-generated invoice.", 4);

  doc.save(`fire-biz-invoice-${sale.invoice_number ?? sale.id.slice(0, 8)}.pdf`);
}
