import { NPR_PER_KRW } from "@/components/savings-tracker/savings-tracker-data";
import type { ReturnToNepalPlannerState } from "@/lib/return-to-nepal/types";

export const RETURN_PLANNER_STORAGE_KEY = "fn-return-to-nepal-planner-v1";

export const DEFAULT_RETURN_PLANNER_STATE: ReturnToNepalPlannerState = {
  koreaSavingsKrw: 118_400_000,
  nepalLiquidNpr: 4_200_000,
  monthlySalaryKrw: 3_400_000,
  salaryGrowthPct: 2.8,
  monthlySavingsKrw: 1_180_000,
  koreaYearsWorked: 6.5,
  plannedKoreaYearsRemaining: 5.8,
  nprPerKrw: NPR_PER_KRW,
  nepalInflationPct: 6.2,
  targetReturnYear: 2032,
  adults: 2,
  children: 1,
  city: "kathmandu",
  lifestyle: "comfortable",
  landBudgetNpr: 8_500_000,
  constructionBudgetNpr: 12_000_000,
  interiorBudgetNpr: 2_800_000,
  furnitureBudgetNpr: 1_400_000,
  homeLoanPrincipalNpr: 6_000_000,
  homeLoanAprPct: 11.25,
  homeLoanYears: 12,
  houseProgressPct: 38,
  completedPhases: ["land", "foundation", "structure"],
  pensionMonthlyNpr: 22_000,
  dividendMonthlyNpr: 8_500,
  fdMonthlyNpr: 35_000,
  rentalMonthlyNpr: 0,
  swpMonthlyNpr: 12_000,
  severanceOverrideKrw: 0,
  nationalPensionMaturityOverrideKrw: 0,
  schoolFeesMonthlyNpr: 28_000,
  relocationOneTimeNpr: 950_000,
  parentSupportMonthlyNpr: 18_000,
  healthcareMonthlyNpr: 14_000,
  emergencyMonthsTarget: 9,
  businessCapitalNpr: 4_500_000,
  expectedRentalYieldPct: 7.5,
  taxReadinessPct: 35,
  bankingChecklistPct: 55,
  propertyDocsPct: 40,
  migrationChecklistPct: 48,
  settlementChecklist: ["nprBanking", "healthNepal"],
};
