import { FALLBACK_KRW_PER_NPR } from "@/lib/exchange-rate";
import type { ReturnToNepalPlannerState } from "@/lib/return-to-nepal/types";

export const RETURN_PLANNER_STORAGE_KEY = "fn-return-to-nepal-planner-v1";

export const DEFAULT_RETURN_PLANNER_STATE: ReturnToNepalPlannerState = {
  koreaSavingsKrw: 0,
  nepalLiquidNpr: 0,
  monthlySalaryKrw: 0,
  salaryGrowthPct: 0,
  monthlySavingsKrw: 0,
  koreaYearsWorked: 0,
  plannedKoreaYearsRemaining: 0,
  nprPerKrw: 1 / FALLBACK_KRW_PER_NPR,
  nepalInflationPct: 0,
  targetReturnYear: new Date().getFullYear() + 5,
  adults: 1,
  children: 0,
  city: "kathmandu",
  lifestyle: "comfortable",
  landBudgetNpr: 0,
  constructionBudgetNpr: 0,
  interiorBudgetNpr: 0,
  furnitureBudgetNpr: 0,
  homeLoanPrincipalNpr: 0,
  homeLoanAprPct: 0,
  homeLoanYears: 0,
  houseProgressPct: 0,
  completedPhases: [],
  pensionMonthlyNpr: 0,
  dividendMonthlyNpr: 0,
  fdMonthlyNpr: 0,
  rentalMonthlyNpr: 0,
  swpMonthlyNpr: 0,
  severanceAutoCalculate: true,
  severanceOverrideKrw: 0,
  nationalPensionAutoCalculate: true,
  nationalPensionMaturityOverrideKrw: 0,
  schoolFeesMonthlyNpr: 0,
  relocationOneTimeNpr: 0,
  parentSupportMonthlyNpr: 0,
  healthcareMonthlyNpr: 0,
  emergencyMonthsTarget: 0,
  businessCapitalNpr: 0,
  expectedRentalYieldPct: 0,
  taxReadinessPct: 0,
  bankingChecklistPct: 0,
  propertyDocsPct: 0,
  migrationChecklistPct: 0,
  settlementChecklist: [],
};
