import { agreementNumber, todayIso, uid, addMonthsIso } from "@/lib/fire-lending/format";
import { buildInstallmentSchedule, refreshInstallmentStatuses } from "@/lib/fire-lending/emi";
import { computeTrustScore, riskFromTrust } from "@/lib/fire-lending/trust-score";
import type { FireLendingStore } from "@/lib/fire-lending/types";

export function createSeedStore(): FireLendingStore {
  const meId = "party_me";
  const aId = "party_anjali";
  const bId = "party_binod";
  const cId = "party_sita";

  const parties = [
    {
      id: meId,
      fireNepalId: "FN-88421",
      name: "You",
      mobile: "9800000001",
      trustScore: 0,
      verified: true,
      rolePreference: "both" as const,
      onTimePayments: 18,
      latePayments: 1,
      loansCompleted: 4,
      identityVerified: true,
      notes: "Primary FIRE Nepal account",
    },
    {
      id: aId,
      fireNepalId: "FN-55102",
      name: "Anjali Shrestha",
      mobile: "9812345678",
      trustScore: 0,
      verified: true,
      rolePreference: "borrower" as const,
      onTimePayments: 11,
      latePayments: 0,
      loansCompleted: 3,
      identityVerified: true,
    },
    {
      id: bId,
      fireNepalId: "FN-66219",
      name: "Binod Gurung",
      mobile: "9823456789",
      trustScore: 0,
      verified: true,
      rolePreference: "lender" as const,
      onTimePayments: 9,
      latePayments: 2,
      loansCompleted: 2,
      identityVerified: true,
    },
    {
      id: cId,
      fireNepalId: "FN-77330",
      name: "Sita Magar",
      mobile: "9834567890",
      trustScore: 0,
      verified: false,
      rolePreference: "borrower" as const,
      onTimePayments: 3,
      latePayments: 3,
      loansCompleted: 1,
      identityVerified: false,
    },
  ].map((p) => ({ ...p, trustScore: computeTrustScore(p) }));

  const loan1Id = uid("loan");
  const loan2Id = uid("loan");
  const loan3Id = uid("loan");
  const start1 = addMonthsIso(todayIso(), -3);
  const start2 = addMonthsIso(todayIso(), -1);
  const start3 = addMonthsIso(todayIso(), -5);

  const loans = [
    {
      id: loan1Id,
      agreementNumber: agreementNumber(),
      role: "lender" as const,
      counterpartyId: aId,
      amount: 150000,
      currency: "NPR" as const,
      interestRate: 12,
      loanType: "personal" as const,
      durationMonths: 12,
      installmentCount: 12,
      gracePeriodDays: 5,
      lateFeePercent: 2,
      purpose: "Home renovation",
      notes: "Family peer loan",
      status: "active" as const,
      createdAt: start1,
      startDate: start1,
      outstanding: 112500,
      totalPaid: 37500,
      interestEarned: 4500,
      connectionMethod: "fire_id" as const,
      borrowerSigned: true,
      lenderSigned: true,
      riskScore: riskFromTrust(parties.find((p) => p.id === aId)!.trustScore, 0),
      guarantor: "Ram Shrestha",
    },
    {
      id: loan2Id,
      agreementNumber: agreementNumber(),
      role: "borrower" as const,
      counterpartyId: bId,
      amount: 80000,
      currency: "NPR" as const,
      interestRate: 10,
      loanType: "peer" as const,
      durationMonths: 6,
      installmentCount: 6,
      gracePeriodDays: 3,
      lateFeePercent: 1.5,
      purpose: "Working capital",
      status: "active" as const,
      createdAt: start2,
      startDate: start2,
      outstanding: 68000,
      totalPaid: 12000,
      interestEarned: 0,
      connectionMethod: "mobile" as const,
      borrowerSigned: true,
      lenderSigned: true,
      riskScore: 28,
    },
    {
      id: loan3Id,
      agreementNumber: agreementNumber(),
      role: "lender" as const,
      counterpartyId: cId,
      amount: 50000,
      currency: "NPR" as const,
      interestRate: 14,
      loanType: "emergency" as const,
      durationMonths: 8,
      installmentCount: 8,
      gracePeriodDays: 0,
      lateFeePercent: 3,
      purpose: "Medical emergency",
      status: "overdue" as const,
      createdAt: start3,
      startDate: start3,
      outstanding: 28000,
      totalPaid: 22000,
      interestEarned: 3200,
      connectionMethod: "invite_link" as const,
      borrowerSigned: true,
      lenderSigned: true,
      riskScore: riskFromTrust(parties.find((p) => p.id === cId)!.trustScore, 2),
      collateral: "Gold jewelry valuation NPR 60,000",
    },
  ];

  const installments = refreshInstallmentStatuses([
    ...buildInstallmentSchedule({
      loanId: loan1Id,
      principal: 150000,
      annualRatePct: 12,
      months: 12,
      startDate: start1,
    }).map((row, idx) =>
      idx < 3 ? { ...row, paidAmount: row.amount, status: "paid" as const } : row,
    ),
    ...buildInstallmentSchedule({
      loanId: loan2Id,
      principal: 80000,
      annualRatePct: 10,
      months: 6,
      startDate: start2,
    }).map((row, idx) => (idx < 1 ? { ...row, paidAmount: row.amount, status: "paid" as const } : row)),
    ...buildInstallmentSchedule({
      loanId: loan3Id,
      principal: 50000,
      annualRatePct: 14,
      months: 8,
      startDate: start3,
    }).map((row, idx) => {
      if (idx < 3) return { ...row, paidAmount: row.amount, status: "paid" as const };
      if (idx === 3) return { ...row, paidAmount: 0, status: "overdue" as const, dueDate: addMonthsIso(todayIso(), -10) };
      return row;
    }),
  ]);

  return {
    currentUserId: meId,
    parties,
    loans,
    installments,
    payments: [
      {
        id: uid("pay"),
        loanId: loan1Id,
        amount: 12500,
        method: "esewa",
        status: "completed",
        paidAt: addMonthsIso(todayIso(), -1),
        isPartial: false,
        isSettlement: false,
        note: "EMI #3",
      },
      {
        id: uid("pay"),
        loanId: loan2Id,
        amount: 12000,
        method: "bank_transfer",
        status: "completed",
        paidAt: addMonthsIso(todayIso(), -0),
        isPartial: false,
        isSettlement: false,
      },
      {
        id: uid("pay"),
        loanId: loan3Id,
        amount: 5000,
        method: "khalti",
        status: "completed",
        paidAt: addMonthsIso(todayIso(), -2),
        isPartial: true,
        isSettlement: false,
        note: "Partial recovery",
      },
    ],
    requests: [
      {
        id: uid("req"),
        fromPartyId: aId,
        toPartyId: meId,
        amount: 100000,
        currency: "NPR",
        interestRate: 11,
        durationMonths: 10,
        purpose: "Shop inventory restock",
        status: "pending",
        createdAt: todayIso(),
        message: "Need short-term working capital. Can repay via eSewa.",
      },
      {
        id: uid("req"),
        fromPartyId: meId,
        toPartyId: bId,
        amount: 40000,
        currency: "NPR",
        interestRate: 9,
        durationMonths: 4,
        purpose: "Bridge until salary",
        status: "changes_requested",
        createdAt: addMonthsIso(todayIso(), 0),
        changeRequest: "Please reduce rate to 8% and add guarantor.",
      },
    ],
    agreements: loans.map((loan) => ({
      id: uid("agr"),
      loanId: loan.id,
      agreementNumber: loan.agreementNumber,
      status: loan.status === "overdue" || loan.status === "active" ? ("active" as const) : ("draft" as const),
      generatedAt: loan.createdAt,
      borrowerSignedAt: loan.borrowerSigned ? loan.startDate : undefined,
      lenderSignedAt: loan.lenderSigned ? loan.startDate : undefined,
      terms: "Standard FIRE Nepal Peer Lending Terms apply. Late fees accrue after grace period.",
      qrPayload: `fire-nepal://verify/agreement/${loan.agreementNumber}`,
    })),
    notifications: [
      {
        id: uid("ntf"),
        kind: "loan_request",
        title: "New loan request",
        body: "Anjali Shrestha requested NPR 100,000 for shop inventory.",
        createdAt: todayIso(),
        read: false,
        href: "/fire-lending/requests",
      },
      {
        id: uid("ntf"),
        kind: "payment_due",
        title: "Payment due soon",
        body: "An installment on your lent portfolio is due this week.",
        createdAt: todayIso(),
        read: false,
        href: "/fire-lending/installments",
      },
      {
        id: uid("ntf"),
        kind: "overdue",
        title: "Overdue alert",
        body: "Sita Magar has an overdue installment. Suggested follow-up available.",
        createdAt: todayIso(),
        read: false,
        href: "/fire-lending/loans",
      },
      {
        id: uid("ntf"),
        kind: "ai_insight",
        title: "AI portfolio tip",
        body: "Collection rate is strong on Anjali’s loan — consider offering a top-up.",
        createdAt: todayIso(),
        read: true,
        href: "/fire-lending/analytics",
      },
    ],
    documents: [
      {
        id: uid("doc"),
        loanId: loan1Id,
        title: "Signed Peer Loan Agreement",
        kind: "agreement",
        createdAt: start1,
      },
      {
        id: uid("doc"),
        partyId: aId,
        title: "Citizenship scan (verified)",
        kind: "id",
        createdAt: start1,
      },
      {
        id: uid("doc"),
        loanId: loan3Id,
        title: "Collateral valuation note",
        kind: "collateral",
        createdAt: start3,
      },
    ],
  };
}
