import type { FamilyModuleState } from "@/lib/family-module/types";

const today = new Date().toISOString().slice(0, 10);

/** Empty workspace — all family data comes from user actions and persistence. */
export const initialFamilyModuleState: FamilyModuleState = {
  stabilityScore: 0,
  upcomingBills: [],
  familyGoals: [],
  emergencyContacts: [],
  hubInsights: [],
  children: [],
  attendanceWeek: [],
  exam: { title: "", subject: "", examDate: today },
  studyStreakDays: 0,
  activityMinutes: [],
  sleepQuality: { score: 0, deepHours: 0, bedTime: "", wakeTime: "", note: "" },
  homework: [],
  tuition: { term: "", paidNpr: 0, totalNpr: 0, nextInstallment: "" },
  gpa: { current: 0, target: 0, term: "" },
  subjects: [],
  educationFund: { monthlySipNpr: 0, yearsToUniversity: 0, projectedCorpusNpr: 0, gapNpr: 0 },
  medicineReminders: [],
  insurance: [],
  vaccinations: [],
  emergencyMedical: { bloodTypes: "", allergies: "", insurerCard: "" },
  calendarEvents: [],
  parentingNotes: [],
  parentingInsights: [],
  familyAlerts: [],
  behaviorInsights: [],
  smartRecommendations: [],
  feePaymentHistory: [],
  examResults: [],
  gpaHistory: [],
  subjectTrendPoints: [],
  vaultDocuments: [],
  vaultTimeline: [],
  documentReminders: [],
  vaultEducationInsights: [],
  schedulePeriods: [],
  examSchedule: [],
  teacherNotes: [],
};
